apiVersion: main.vishu42.github.io/v1beta1
kind: AzureSecretSync
metadata:
  labels:
    app.kubernetes.io/name: github-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: azure-secretsync-sample
spec:
  azureKeyVault:
    vaultName: "vault-name"
    tenantId: "tenant-id"
    clientId: "client-id"
    clientSecret: 
      valueFromSecret:
        name: my-secret
        key: client-secret
  github:
    token: 
      valueFromSecret:
        name: my-secret
        key: github-token
    owner: "Owner"
    repo: "Repo" # Optional, only for repo or environment-level secrets
    environment: "poc"   # Optional, only for environment-level secrets
    secretLevel: "environment"  # Can be "repo", "org", or "environment"
  mappings:
    - keyVaultSecret: "postgres-admin-password-staging"
      githubSecret: "POSTGRES_ADMIN_PASSWORD"
    - keyVaultSecret: "postgres-admin-username-staging"
      githubSecret: "POSTGRES_ADMIN_USERNAME"
