apiVersion: main.vishu42.github.io/v1beta1
kind: SecretSync
metadata:
  labels:
    app.kubernetes.io/name: github-secrets-operator
    app.kubernetes.io/managed-by: kustomize
  name: secretsync-sample
spec:
  azureKeyVault:
    vaultName: "my-key-vault"
    tenantId: "your-tenant-id"
    clientId: "your-client-id"
    clientSecret: "your-client-secret"
  github:
    repoName: "your-github-repo"
    token: "your-github-token"
  mappings:
    - keyVaultSecret: "postgres-admin-password-staging"
      githubSecret: "POSTGRES_ADMIN_PASSWORD"
    - keyVaultSecret: "postgres-admin-username-staging"
      githubSecret: "POSTGRES_ADMIN_USERNAME"
